name: Send Reminder Emails

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  send-reminder-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: https://hackathons.hackclub.com/api/trigger-reminder
          CONFIGURATION: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.TOKEN }}"} }'
